### PR TITLE
Allow setting the timeout with the "timeout" URL parameter

### PR DESCRIPTION
**Pull request by evalstate**
Allows setting the Request Timeout in milliseconds with a "timeout" URL parameter

## Motivation and Context

Enables testing of tools which take > 10s to respond.

## How Has This Been Tested?

This has been tested using the mcp-everything server 

image

## Breaking Changes

No breaking changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist

- [X] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [X] My code follows the repository's style guidelines
- [X] New and existing tests pass locally
- [X] I have added appropriate error handling
- [X] I have added or updated documentation as needed

## Additional context

@ashwin-ant this is intended to cover simple cases - I considered matching progress updates to requestids to reset the timer - but that seems over-engineered for the need.

### CODE REVIEW

**Review by ashwin-ant — DISMISSED** [review]
Thank you!

**Comment by evalstate** [comment]
Build failing - think it is related to this commit in the SDK: 

https://github.com/modelcontextprotocol/typescript-sdk/commit/e911ece970934f614f1ab61d349e7f3ecf162140

Will fix.

**Comment by ashwin-ant** [comment]
@evalstate I have a PR open to update the SDK https://github.com/modelcontextprotocol/inspector/pull/101

**Comment by evalstate** [comment]
OK. I've added a commit - I'll wait for that to go through and merge. Best.

**Comment by jspahrsummers** [comment]
Sorry about the breakage here! Per discussion on https://github.com/modelcontextprotocol/inspector/pull/101, didn't mean to release this breaking change—working on fixing it up now 😟

**Comment by ashwin-ant** [comment]
@evalstate I've updated the SDK to 1.0.3, mind rebasing this PR (and removing the second commit)?

**Comment by evalstate** [comment]
Rebased; commits tidied.

**Review by ashwin-ant — APPROVED** [review]

**Pull request merged**
